const {
    NEXT_PUBLIC_API_BASE_URL = "http://localhost:8080/webapi/",
    NEXT_PUBLIC_APP_BACKEND_URL = "http://localhost:8080",
    NEXT_PUBLIC_APP_SOCKET_URL = "http://localhost:8080",
    NEXT_PUBLIC_APP_FRONTEND_URL = "http://localhost:3000",
    NEXT_PUBLIC_APP_FRONEND_URL_PRINT = "devexchange.test.com",
    APP_SITENAME = "dev-exchange",
    APP_THEME_NAME = "siteTheme",
    APP_MAINTENANCE_STATUS = "Disable"
} = process.env;

const KEY = {
    V1_API_URL: NEXT_PUBLIC_API_BASE_URL + "v1/",
    V2_API_URL: NEXT_PUBLIC_API_BASE_URL + "v2/",
    BACKEND_URL: NEXT_PUBLIC_APP_BACKEND_URL,
    SOCKET_URL: NEXT_PUBLIC_APP_SOCKET_URL,
    FRONTEND_URL: NEXT_PUBLIC_APP_FRONTEND_URL,
    FRONEND_URL_PRINT: NEXT_PUBLIC_APP_FRONEND_URL_PRINT,
    SITENAME: APP_SITENAME,
    THEME_NAME: APP_THEME_NAME,
    MAINTENANCE_STATUS: APP_MAINTENANCE_STATUS,
};

export default KEY;

